### ISSUE TITLE
Package assumes that it is being required from root of project.

### ISSUE THREAD

**Issue by theophoric** [IBM-Cloud/cf-deployment-tracker-client-node#9]
From `track.js`:

`var pkg = require(path.join(path.dirname(module.parent.filename), 'package.json')),`

Does not work if application entry point is in, for example, `server/server.js` as in this error:
`2016-07-22T09:51:34.61-0300 [App/0] ERR Error: Cannot find module '/home/vcap/app/server/package.json'`

**Comment by germanattanasio** [comment]
I'm hitting the same issue so I decided to remove the `cf-deployment-tracker` for now.

**Comment by ptitzler** [comment]
Proposing solution that doesn't require any changes to the app that is being tracked: https://github.com/IBM-Bluemix/cf-deployment-tracker-client-node/pull/11. It should satisfy the common tracking scenarios:

- sample app invokes tracking routine
- sample app loads local module that invokes tracking routine
- sample app loads remote module that invokes tracking routine

Tracking requests are only submitted if `package.json` can be loaded to avoid incomplete tracking records.

**Comment by ptitzler** [comment]
Delivered by #11.

**Comment by ptitzler** [comment]
It appears that the implemented solution does not return the expected results in certain scenarios. For example, if an app `a` requires a module `b` that has been enabled for deployment tracking, `a`'s `package.json` is loaded instead of ` `b` 's. Therefore DT actually creates a tracking record for `a` and not `b`.
